[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "npx pnpm@8.15.0 install"
]

[phases.build]
cmds = [
  "cd apps/web && npx pnpm@8.15.0 build"
]

[start]
cmd = "cd apps/web && npx --yes serve -s dist -l 3000"