[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[phases.setup]
nixPkgs = ["nodejs_22", "corepack"]

[phases.install]
cmds = [
  "corepack enable",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "cd apps/web && pnpm build"
]

[start]
cmd = "echo 'Static site generated successfully'"