[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "npx pnpm@8.15.0 install --frozen-lockfile"
]

[phases.build]
cmds = [
  "cd apps/web && npx pnpm@8.15.0 build"
]

[start]
cmd = "echo 'Static site generated successfully'"